Promise.reject(1).then(null, error => {
  console.log(error);
});

Promise.reject(1).catch(err => {
  console.log(console.error(););
});
